---
# glusterfs_clients/handlers/main.yml

- name: 'Trigger systemctl daemon-reload'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart the glusterfs mount'
  ansible.builtin.service:
    name: "{{ mount_unit_name.stdout }}"
    state: 'restarted'
